Repository chingu-x/chingu-dashboard-be, pull requests merged in 2024-10, with the labels that each got.

#205 Fix CORS origin localhost entry
  CHANGELOG.md
  src/main.ts
Labels: review, medium

#202 Add github workflow for PR reminder
  .github/workflows/pr-reviwer-reminder.yml
  CHANGELOG.md
Labels: review, low

#211 update regex in origin list
  CHANGELOG.md
  src/main.ts
Labels: review, high

#212 add same site property to cookie
  CHANGELOG.md
  src/auth/auth.service.ts
Labels: review, high

#210 Update docker compose to use timescaledb
  CHANGELOG.md
  docker-compose.yml
Labels: review, low

#186 Fix/checkin submit
  CHANGELOG.md
  src/ability/conditions/sprints.ability.ts
  src/global/types/global.types.ts
  src/global/types/voyage.types.ts
  src/sprints/sprints.response.ts
  src/sprints/sprints.service.ts
  test/sprints.e2e-spec.ts
Labels: review, low

#214 add same site property to the cookie sent in the refresh endpoint
  CHANGELOG.md
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: review

#206 chore: update user voyage roles in dev seed
  CHANGELOG.md
  prisma/seed/users.ts
  prisma/seed/voyage-teams.ts
  prisma/seed/voyage.ts
Labels: review, medium

#213 Feature: Solo Projects Part 1 - Database schema + basic seed
  CHANGELOG.md
  README.md
  prisma/migrations/20241009120111_update_solo_project_model/migration.sql
  prisma/schema/comment.prisma
  prisma/schema/soloproject.prisma
  prisma/schema/user.prisma
  prisma/seed/solo-project.ts
Labels: review

#218 add same site property to logout method and update cors origin list
  CHANGELOG.md
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/main.ts
Labels: review

#208 Teams can create own tech categories
  CHANGELOG.md
  prisma/migrations/20241023191037_update_techstack_categories_schema/migration.sql
  prisma/schema/teamStack.prisma
  prisma/schema/voyage.prisma
  prisma/seed/data/tech-stack-categories.ts
  prisma/seed/seed.ts
  prisma/seed/tables.ts
  prisma/seed/voyage-teams.ts
  src/global/types/CustomRequest.ts
  src/techs/dto/create-techstack-category.dto.ts
  src/techs/dto/update-tech.dto.ts
  src/techs/dto/update-techstack-category.dto.ts
  src/techs/techs.controller.ts
  src/techs/techs.response.ts
  src/techs/techs.service.ts
Labels: review, high

#219 Tests/ideations unit tests
  CHANGELOG.md
  src/ideations/ideations.controller.spec.ts
  src/ideations/ideations.service.spec.ts
Labels: review
