Repository chingu-x/chingu-dashboard-be, pull requests merged in 2024-09, with the labels that each got.

#197 Bug: add check for team id in place of memberId
  CHANGELOG.md
  src/features/features.service.ts
  test/features.e2e-spec.ts
Labels: bug

#199 Update docker compose and localhost port
  CHANGELOG.md
  docker-compose.yml
  package.json
  src/main.ts
Labels: review

#198 Fix/checkin form check question
  CHANGELOG.md
  src/global/global.service.ts
  src/sprints/sprints.service.ts
  src/voyages/voyages.service.ts
Labels: review

#193 Feat: CASL permission voyage sprints
  CHANGELOG.md
  src/ability/ability.factory/ability.factory.ts
  src/ability/conditions/meetingOrAgenda.ability.ts
  src/ability/prisma-generated-types.ts
  src/sprints/sprints.controller.ts
  src/sprints/sprints.service.ts
  test/sprints.e2e-spec.ts
Labels: feature

#200 Add middleware morgan to log all requests for debug
  CHANGELOG.md
  package.json
  src/main.ts
  src/middleware/requests-logging.ts
  yarn.lock
Labels: review

#201 Test: unit tests for Team resources
  CHANGELOG.md
  src/resources/resources.controller.spec.ts
  src/resources/resources.service.spec.ts
Labels: review

#204 test: unit test for forms controller and services
  CHANGELOG.md
  src/forms/forms.controller.spec.ts
  src/forms/forms.service.spec.ts
Labels: review

#209 Fix/voyage sprints get teamid
  CHANGELOG.md
  src/sprints/sprints.controller.ts
  src/sprints/sprints.service.ts
Labels: review, high

#207 refactor: changed E2E import paths to use '@/'
  CHANGELOG.md
  src/auth/auth.module.ts
  src/development/development.module.ts
  src/tasks/tasks.module.ts
  test/app.e2e-spec.ts
  test/development.e2e-spec.ts
  test/features.e2e-spec.ts
  test/jest-e2e.json
  test/teams.e2e-spec.ts
  test/unverifiedUser.e2e-spec.ts
  test/users.e2e-spec.ts
Labels: review, low
